spring.application.name=teamWork

# ?????????? ???? ? H2 ?????
application.recommendations-db.url=jdbc:h2:file:C:/Users/sergf/java%20projects/teamWork/transaction
#spring.datasource.url=jdbc:h2:file:C:/Users/sergf/java%20projects/teamWork/transaction
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 ??????? (??? ????????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate ????????????? ?? ????? ??????? ???????
spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=never

# for Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
